### ISSUE TITLE
Introducing LangChain to base babyagi

### ISSUE THREAD

**Issue by MalikMAlna** [yoheinakajima/babyagi#150]
Been seeing a lot of YouTubers adding LangChain agents for giving babyagi more functionality for its task completion. This issue is similar to #96, but I wanted to go a bit further with adding Langchain throughout the whole architecture along with more than just search agents, like optional APIs for more modular functionality with other toolsets. 

Would that be alright? 

Just wanted to gauge interest from the community and @yoheinakajima before moving forward on those more heavy-set changes to the code.

**Comment by Ryangr0** [comment]
Honestly if you want to go this route I would say let's start getting some abstraction in here etc. I'd be super interested in a PR regardless of whether it gets merged or not. I've been messing around with it a couple of hours as well, implementing weaviate instead of pinecone. I'd love to see a more general solution for this.

**Comment by moover-shaker** [comment]
@Ryangr0 @Ryangr0 - I would be interested in this and can contribute some development. Have good working knowledge of langchain but newbe on babyagi.

**Comment by Ryangr0** [comment]
> @Ryangr0 @MalikMAlna - I would be interested in this and can contribute some development. Have good working knowledge of langchain but newbe on babyagi.

I have been working on this the past few days and thinking about it since I saw this repository.

https://github.com/webgrip/PuttyGPT/tree/master/Eve This is how far I've gotten so far. You're free to take a look through the scripts or the readme for an explanation of what's in there.

**Comment by moover-shaker** [comment]
@Ryangr0 - Briefly looked at your code and it’s a good start. Also like your idea to start with some abstraction and architecture discussions. Requirements discussion would also be very helpful before doing too much more coding. Also check out [BabyAgi streamlit using LangChain](https://github.com/dory111111/babyagi-streamlit). Oh, and, BTW, get some sleep 😴

**Comment by Ryangr0** [comment]
I completely agree, this should probably stay a stepping stone like it is for a lot of us, I love this collaborative spirit. Just for context, all the code that pertains to babyagi that I refactored, is in [here](https://github.com/webgrip/PuttyGPT/tree/master/Eve/toddlerapi). Maybe you can get some ideas from there.

**Comment by MalikMAlna** [comment]
Yeah @Ryangr0, I’m probably gonna use that as a reference, likely setting up a relatively simple change similar to something in your implementation and from there we can discuss it further on the PR to see if we’d need to refactor or if it’s good to be reviewed and merged.

**Comment by MalikMAlna** [comment]
Okay, I got a PR up, I started with something very simple by adding LangChain to the requirements.txt and separating out the main loop into its own function that can run any LangChain implementation we end up going with as a group. 

It's not much, but it's a start and break of anything. Let me know what you all think as I'm still new to LangChain and not 100% sure where to start with a full implementation.

**Comment by Ryangr0** [comment]
>  

If I'm being completely honest, I think my repo had a good thing going on on main.py and the relating classes/files, you're free to copy it to here if you want, or just gain some inspiration, whatever. That's the result of me struggling with chatgpt's help for almost 3 days now. In a bit I'll have it analyze all the code and write a summary of what I'm doing. Lol I can't believe this is reality now.

**Comment by MalikMAlna** [comment]
Yeah, I'm mostly leaning toward your implementation @Ryangr0. I think it's the cleanest and you've actually given permission for using it in the code here.

I would appreciate the summary though. I have an idea as to what it's doing, but documenting each part would really help so I think I'm gonna on that for right now before moving forward.

**Comment by MalikMAlna** [comment]
That being said, I have also been reading some of your toddleragi files and those seem like they could work as well for a long-term full implementation.

**Comment by Ryangr0** [comment]
Be aware though that even right now, in my local environment, it's not fully working. I got it working, then it broke, then I refactored, then it broke again, it's one of those things. But every moment I'm getting closer to stability. I'm still having a hard time with the concept of chains, agents and tools. I think a lot of people use a lot of words completely interchangeably and it makes it hard to know what's going on. Especially with python's wonky **kwargs stuff lol, I've never worked with python for longer than a few minutes before. Fun experience, for sure.

**Comment by moover-shaker** [comment]
One (of several) nice things about your approach @Ryangr0 is a more complete integration of LangChain. The streamlit repo was really just using LangChain as conduit to OpenAI instead of using the nice LangChain (LC) abstraction to DOZENS of AI providers (Cohure, AI21, etc.). 

If I can help a little, **kwargs are just what Python calls “unpacking”. If your familiar with c++ it’s somewhat like derefferencing a pointer or like a spread operator in JavaScript. The analogy is not perfect though. RealPython site has a good explanation [here](https://realpython.com/python-kwargs-and-args/).

We haven’t started our abstraction discussion yet (I guess we are now 😀) but I was envisioning that we could us LC’s agent as a “router” or “supervisor” agent to control its tools. We may need to write custom LC agent or tools to implement BabyAGI in (this is not hard, I’ve written several).

And, at another level, we may want to even abstract LC away from the current BabyAGI to make an easier transition and also since some users might find LC too heavyweight (I see that AutoGPT started with LC but stripped it out, might be nice to know why).

@MalikMAlna - it would be nice to have a good place to have these discussions and store resultant documents on GitHub. Any suggestions or thoughts?

**Comment by moover-shaker** [comment]
[Custom tools](https://python.langchain.com/en/latest/modules/agents/tools/custom_tools.html)

[Custom agents](https://python.langchain.com/en/latest/modules/agents/agents/custom_agent.html)

**Comment by Ryangr0** [comment]
> One (of several) nice things about your approach @Ryangr0 is a more complete integration of LangChain. The streamlit repo was really just using LangChain as conduit to OpenAI instead of using the nice LangChain (LC) abstraction to DOZENS of AI providers (Cohure, AI21, etc.).
> 
> If I can help a little, **kwargs are just what Python calls “unpacking”. If your familiar with c++ it’s somewhat like derefferencing a pointer or like a spread operator in JavaScript. The analogy is not perfect though. RealPython site has a good explanation [here](https://realpython.com/python-kwargs-and-args/).
> 
> We haven’t started our abstraction discussion yet (I guess we are now 😀) but I was envisioning that we could us LC’s agent as a “router” or “supervisor” agent to control its tools. We may need to write custom LC agent or tools to implement BabyAGI in (this is not hard, I’ve written several).
> 
> And, at another level, we may want to even abstract LC away from the current BabyAGI to make an easier transition and also since some users might find LC too heavyweight (I see that AutoGPT started with LC but stripped it out, might be nice to know why).
> 
> @MalikMAlna - it would be nice to have a good place to have these discussions and store resultant documents on GitHub. Any suggestions or thoughts?

It is my opinion that it wouldn't make much sense to refactor this library completely to use a framework. I think I get what you're going for, but the actual "recursive" loop that was demonstrated in this project isn't technically such a difficult concept to implement. The idea was 👌 though. That's why I refactored a little bit of babyagi and named it toddleragi (as well as wanting to know more about the weaviate python client), so that I could then work on PuttyGPT by implementing that loop.

Anyway, the point was, it's up to you. I think this repository would be a great, example of some small usecases with a minimal implementation to get people in the door.  ...That's not to say it can't look nice :)

I have many ideas. But I need to go to sleep soon. I'm going to write them down in my repo so I can keep track of it in one place and close my eyes.

Am I saying something crazy when I say that I just need to work on this until the script can literally just rewrite itself to be better and I don't even need to commit anything anymore? Make new scripts, make new agents, read papers, read blogs, scrape API's, automatically keep track of new developments in the field, on huggingface, in weaviate, build a long and short term memory and more. I feel like I'm almost there...

**Comment by MalikMAlna** [comment]
Hey @Ryangr0, I decide to take the code for the toddleragi work you were doing for personal reference on a full implementation. 

I managed to get it working up to the point where you left off on your todo. Here's what it looks like in the babyagi code in this branch I set up: https://github.com/MalikMAlna/babyagi/tree/langchain-full-implementation

I left most everything in the extensions folder aside from the toddleragi file that I left in root. Also, I left out Weaviate for now because I wanted to focus on Pinecone since I'm more familiar with that vector db. 

Let me know if you have any thoughts.

**Comment by moover-shaker** [comment]
@MalikMAlna - that’s a good approach.

**Comment by Ryangr0** [comment]
> @Ryangr0 - BEFORE READING THIS, GET SOME SLEEP. When you wake up and have some breakfast an d coffee, read on…
> 
> So….are you proposing a whole new open source project “inspired by” BabyAGI but not using any of its code, based fully on LC? That is certainly one alternative. I would like to see what @MalikMAlna and others think about that.
> 
> Another alternative is to break out an AiEngine layer with an AiEngineFactory (both abstract classes) and have two implementations of AiEngine:
> 
> 1. AiLangChainEngine - based on pure LC implementation (ala your Eve (great name, BTW))
> 2. AiNativePythonEngine - based on (slightly refactored) current BabyAGI code, all in Python with no heavy weight 3rd party libraries.
> 
> AiEngineFactory (which may actually not be abstract, not sure) would have a createAiEngine(aiEngineName) method that would create one or the other concrete ai engine classes. Not sure exactly where the abstraction would be but one option is to have something like a AiEngine:runLoop() method (though this is TBD).
> 
> This has two advantages:
> 
> 1. Keeps this in the existing BabyAGI community along with its traction and developers.
> 2. Allows switching between a lighter engine with less functionality and a heavier engine with more functionality.
> 
> it does have (at least) the disadvantage of an additional abstraction layer, with is not always justified.
> 
> As for your sprint goals, that are highly commendable and I really think we can get there soon. But it’s a bit ambitious for the first step. Would be great to see the ABSOLUTE MINIMUM running version of Eve first so we can clone it and start to help you code together.

I woke up refreshed! Crazy stuff, I was up for over 48 hours and didn't feel tired at all, lol. 

Hmmm, good idea. We should abstract this stuff. There will be standards for certain things within the community so it would be great to know if there are any projects doing this currently. I know of certain ethics standards.

Langchain has so much utility code, but most if it is (in my humble opinion) completely unreadable and even inconsistent. Not the quality a framework wants to be at, but I see the churn and people are hard at work. Think concurrent requests, implementation capabilities of abstracts they defined (introduction of some concepts such as Tools, Agents and Chains. These are great concepts to think around. Before we abstract things I would like to have more insight into what people need to end up using for certain tasks.

We can be sure of a few things:
- We need to be able to communicate with OpenAPI (or other LLMs, api clients are implementation details)
- We need the possibility to use a vectorstore implementation
- We need prompts
- We need the concept of tools in there too somewhere,
- I'm probably missing some stuff but you get the point.

To give a concrete answer, I would personally (and I am) making code that for now relies on langchain. It's an active community where we can be certain the interest of developers that experiment with AI stuff will converge. That's the best way to start narrowing down on the patterns we can see emerging from this new branch of engineering.

**Comment by radman-rt** [comment]
@Ryangr0 -- Totally agree with everything you said. I think there's real value in trying to keep both the BabyAGI and LC communities involved.

I did a clone of @MalikMAlna's forked [langchain-full-implementation](https://github.com/MalikMAlna/babyagi/tree/langchain-full-implementation) branch and see quite a few differences between this and the toddleragi in your [PuttyGPT repo](https://github.com/webgrip/PuttyGPT/blob/master/Eve/toddleragi/toddleragi.py) . Some are minor (adding langchain to requirements.tx) but some are larger. Seems like you're using Weaviate in your toddleragi whereas the fork is using Pinecone. As an aside, LC already has built-in support for both of these:

- https://python.langchain.com/en/latest/ecosystem/pinecone.html
- https://python.langchain.com/en/latest/ecosystem/weaviate.html

But we can refactor to use those later.

Which of these two vectorstores are in your latest thinking? Weaviate? If so, would it be possible to update @MalikMAlna 's fork with your latest code?

Also, I don't see anything in @MalikMAlna fork that allows setting of the OPEN_API_KEY in env vars or elsewhere (maybe just missing this?).

@MalikMAlna -- Any chance you could set @Ryangr0 and myself up as contributors to your fork? And also enable Issues in the Github repo settings so we can start putting some of our discussions in there?

**Comment by radman-rt** [comment]
If I can get the @MalikMAlna fork up and running (at least minimally), I will attempt an quick abstraction of BabyAGI and toddleragi in the next few days.

**Comment by Ryangr0** [comment]
Mine is weaviate, my project has a docker-compose file that runs the following services when I up:

```
version: '3.4'
services:
  weaviate:
    container_name: weaviate
    command:
    - --host
    - 0.0.0.0
    - --port
    - '9001'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.18.3
    ports:
    - 9001:8080
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QNA_INFERENCE_API: 'http://qna-transformers:8080'
      IMAGE_INFERENCE_API: 'http://i2v-neural:8080'
      NER_INFERENCE_API: 'http://ner-transformers:8080'
      SUM_INFERENCE_API: 'http://sum-transformers:8080'
      SPELLCHECK_INFERENCE_API: 'http://text-spellcheck:8080'
      OPENAI_APIKEY: 
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,qna-transformers,ner-transformers,sum-transformers,text-spellcheck,img2vec-neural,ref2vec-centroid,generative-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - /var/weaviate:/var/lib/weaviate
    networks:
      - weaviate-network
      - putty-network
  t2v-transformers:
    container_name: t2v-transformers
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'
  qna-transformers:
    container_name: qna-transformers
    image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
    environment:
      ENABLE_CUDA: '0'
  ner-transformers:
    container_name: ner-transformers
    image: semitechnologies/ner-transformers:dbmdz-bert-large-cased-finetuned-conll03-english
    environment:
      ENABLE_CUDA: '0'
  sum-transformers:
    container_name: sum-transformers
    image: semitechnologies/sum-transformers:facebook-bart-large-cnn-1.0.0
    environment:
      ENABLE_CUDA: '0'
  text-spellcheck:
    container_name: text-transformers
    image: semitechnologies/text-spellcheck-model:pyspellchecker-en
  i2v-neural:
    container_name: i2v-transformers
    image: semitechnologies/img2vec-pytorch:resnet50
    environment:
      ENABLE_CUDA: '0'

networks:
  default:
    name: weaviate-network

  putty-network:
    external: true
```

This means there is no using of a (potentially paid) 3rd party service to store our data or go down or some other things that are outside our control. That's also why I use searxNG for running search engine queries, and on top of that it provides enhanced privacy. AND you don't have to pay for google. Amazing.
